config-version: 2
name: 'gcp_observability_dbt'
version: '0.0.1'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  gcp_observability_dbt:
    gcp_log_source:
      +materialized: view
      +schema: gcp_observability

vars:
  gcp_log_source:
    gcp_log_activity: "{{ source('gcp_log_source','cloudaudit_googleapis_com_activity_*') }}"
    gcp_log_data_access: "{{ source('gcp_log_source','cloudaudit_googleapis_com_data_access_*') }}"
